# Generated by Django 5.2.1 on 2025-09-29 00:24

import django.db.models.deletion
import votingApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Election Title')),
                ('scope', models.CharField(choices=[('department', 'Departmental'), ('faculty', 'Faculty'), ('school', 'SRA')], default='school', max_length=500)),
                ('department', models.CharField(blank=True, choices=[('biology_education', 'Biology Education'), ('business_education', 'Business Education'), ('chemistry_education', 'Chemistry Education'), ('computer_science_education', 'Computer Science Education'), ('economics_education', 'Economics Education'), ('educational_management', 'Educational Management'), ('english_education', 'English Education'), ('guidance_and_counseling', 'Guidance And Counseling'), ('library_and_information_science', 'Library And Information Science'), ('physics_education', 'Physics Education'), ('religious_education', 'Religious Education'), ('social_studies_education', 'Social Studies Education'), ('sacred_theology', 'Sacred Theology'), ('theology', 'Theology'), ('beng_computer_engineering', 'B.Eng Computer Engineering'), ('beng_electrical_electronic_engineering', 'B.Eng Electrical & Electronic Engineering'), ('medical_laboratory_sciences', 'Medical Laboratory Sciences'), ('nursing', 'Nursing'), ('english_literary_studies', 'English & Literary Studies'), ('history_international_relations', 'History & International Relations'), ('philosophy', 'Philosophy'), ('religious_studies', 'Religious Studies'), ('sacred_philosophy', 'Sacred Philosophy'), ('law', 'Law'), ('public_international_law', 'Public & International Law'), ('accounting', 'Accounting'), ('banking_finance', 'Banking & Finance'), ('business_administration', 'Business Administration'), ('entrepreneurial_studies', 'Entrepreneurial Studies'), ('marketing_advertising', 'Marketing & Advertising'), ('public_administration', 'Public Administration'), ('anatomy', 'Anatomy'), ('medicine_and_surgery', 'Medicine and Surgery'), ('physiology', 'Physiology'), ('applied_mathematics', 'Applied Mathematics'), ('applied_microbiology', 'Applied Microbiology'), ('biochemistry', 'Biochemistry'), ('botany', 'Botany'), ('computer_science', 'Computer Science'), ('industrial_chemistry', 'Industrial Chemistry'), ('physics_electronics', 'Physics with Electronics'), ('software_engineering', 'Software Engineering'), ('zoology', 'Zoology'), ('pharmacy', 'Pharmacy'), ('economics', 'Economics'), ('mass_communication', 'Mass Communication'), ('peace_conflict_studies', 'Peace and Conflict Studies'), ('political_science_diplomacy', 'Political Science & Diplomacy')], max_length=100, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('education', 'College of Education'), ('theology', 'Ecclesiastical Faculty of Theology'), ('engineering', 'Faculty of Engineering'), ('health_sciences', 'Faculty of Health Sciences'), ('humanities', 'Faculty of Humanities'), ('law', 'Faculty of Law'), ('management_sciences', 'Faculty of Management Sciences'), ('medical_sciences', 'Faculty of Medical Sciences'), ('natural_applied_sciences', 'Faculty of Natural & Applied Sciences'), ('pharmaceutical_sciences', 'Faculty of Pharmaceutical Sciences'), ('social_sciences', 'Faculty of Social Sciences')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[votingApp.models.validate_video])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.candidate')),
                ('election', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='votingApp.election')),
            ],
            options={
                'verbose_name': 'Candidacy',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='votingApp.election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='positions',
            field=models.ManyToManyField(through='votingApp.Candidacy', to='votingApp.position'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.position'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.candidacy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(fields=('candidate', 'position'), name='candidacy_constraints'),
        ),
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(fields=('candidate', 'election'), name='election_constraints'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'voting_for'), name='unique vote'),
        ),
    ]
