# Generated by Django 5.2.1 on 2025-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0002_remove_vote_unique_vote_vote_unique_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ig_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='snap_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='x_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
