# Generated by Django 5.2.1 on 2025-10-09 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0003_candidate_ig_url_candidate_snap_url_candidate_x_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
