# Generated by Django 5.2.1 on 2025-09-29 00:24

import django.utils.timezone
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('biology_education', 'Biology Education'), ('business_education', 'Business Education'), ('chemistry_education', 'Chemistry Education'), ('computer_science_education', 'Computer Science Education'), ('economics_education', 'Economics Education'), ('educational_management', 'Educational Management'), ('english_education', 'English Education'), ('guidance_and_counseling', 'Guidance And Counseling'), ('library_and_information_science', 'Library And Information Science'), ('physics_education', 'Physics Education'), ('religious_education', 'Religious Education'), ('social_studies_education', 'Social Studies Education'), ('sacred_theology', 'Sacred Theology'), ('theology', 'Theology'), ('beng_computer_engineering', 'B.Eng Computer Engineering'), ('beng_electrical_electronic_engineering', 'B.Eng Electrical & Electronic Engineering'), ('medical_laboratory_sciences', 'Medical Laboratory Sciences'), ('nursing', 'Nursing'), ('english_literary_studies', 'English & Literary Studies'), ('history_international_relations', 'History & International Relations'), ('philosophy', 'Philosophy'), ('religious_studies', 'Religious Studies'), ('sacred_philosophy', 'Sacred Philosophy'), ('law', 'Law'), ('public_international_law', 'Public & International Law'), ('accounting', 'Accounting'), ('banking_finance', 'Banking & Finance'), ('business_administration', 'Business Administration'), ('entrepreneurial_studies', 'Entrepreneurial Studies'), ('marketing_advertising', 'Marketing & Advertising'), ('public_administration', 'Public Administration'), ('anatomy', 'Anatomy'), ('medicine_and_surgery', 'Medicine and Surgery'), ('physiology', 'Physiology'), ('applied_mathematics', 'Applied Mathematics'), ('applied_microbiology', 'Applied Microbiology'), ('biochemistry', 'Biochemistry'), ('botany', 'Botany'), ('computer_science', 'Computer Science'), ('industrial_chemistry', 'Industrial Chemistry'), ('physics_electronics', 'Physics with Electronics'), ('software_engineering', 'Software Engineering'), ('zoology', 'Zoology'), ('pharmacy', 'Pharmacy'), ('economics', 'Economics'), ('mass_communication', 'Mass Communication'), ('peace_conflict_studies', 'Peace and Conflict Studies'), ('political_science_diplomacy', 'Political Science & Diplomacy')], max_length=200)),
                ('faculty', models.CharField(choices=[('education', 'College of Education'), ('theology', 'Ecclesiastical Faculty of Theology'), ('engineering', 'Faculty of Engineering'), ('health_sciences', 'Faculty of Health Sciences'), ('humanities', 'Faculty of Humanities'), ('law', 'Faculty of Law'), ('management_sciences', 'Faculty of Management Sciences'), ('medical_sciences', 'Faculty of Medical Sciences'), ('natural_applied_sciences', 'Faculty of Natural & Applied Sciences'), ('pharmaceutical_sciences', 'Faculty of Pharmaceutical Sciences'), ('social_sciences', 'Faculty of Social Sciences')], max_length=200)),
                ('matNo', models.CharField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            managers=[
                ('objects', members.models.StudentManager()),
            ],
        ),
    ]
